sara_arm_velocity_controller:
  type: "velocity_controllers/JointGroupVelocityController"
  publish_rate: 50               # default: 50
  joints:
   - ca_joint1
   - ca_joint2
   - ca_joint3
   - ca_joint4
   - ca_joint5
   - ca_joint6
